version: '3'

services:
  elucidate_db:
    container_name: elucidate_db
    image: postgres:13-alpine
    shm_size: 1g
    networks:
      - elucidate_network
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elucidate
      - POSTGRES_DB=annotations
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
      
  elucidate_server:
    container_name: elucidate_server
    image: brambdocker/huc-elucidate-server:1.6.0
    networks:
      - elucidate_network
      - nginxproxynetwork
    environment:
      - VIRTUAL_HOST=elucidate.tt.di.huc.knaw.nl
      - VIRTUAL_PORT=8080
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=elucidate
      - DATABASE_URL=jdbc:postgresql://elucidate_db:5432/annotations
      - DB_USER=postgres
      - DB_PASSWORD=elucidate
      - DB_URL=jdbc:postgresql://elucidate_db:5432/annotations
      - BASE_SCHEME=https
      - BASE_PORT=443
      - BASE_HOST=elucidate.tt.di.huc.knaw.nl
      - AUTH_TOKEN_VERIFIERKEY=notinuse
    depends_on:
      - elucidate_db
    tty: true
    expose:
      - 8080
    volumes:
      - ./scripts:/scripts
    command: [ "/scripts/wait-for-it.sh", "elucidate_db:5432", "-t", "120", "--", "./bin/catalina.sh", "run" ]

networks:
  elucidate_network:
  nginxproxynetwork:
    external:
      name: nginxproxynetwork

volumes:
  database-data:
    driver: local