version: '3'
services:
  database:
    container_name: elucidate_db
    image: postgres:13-alpine
    shm_size: 1g
    networks:
      - elucidate_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elucidate
      - POSTGRES_DB=annotations
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
  web:
    container_name: elucidate_server
    image: registry.diginfra.net/tt/huc-elucidate-server:1.6.4
    networks:
      - elucidate_network
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=elucidate
      - DATABASE_URL=jdbc:postgresql://database:5432/annotations
      - AUTH_TOKEN_VERIFIERKEY=notinuse
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ../../scripts:/scripts
    command: ["/scripts/wait-for-it.sh", "database:5432", "--", "./bin/catalina.sh", "run"]

networks:
  elucidate_network:

volumes:
  database-data:
    driver: local
