version: '3'
services:
  database:
    container_name: elucidate_db
    image: postgres:13-alpine
    shm_size: 1g
    networks:
      - elucidate_network
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
#      - database-data:/tmp/postgresql/data/

#  elasticsearch:
#    container_name: elucidate_es
#    image: elasticsearch:7.16.1
#    networks:
#      - elucidate_network
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    restart: unless-stopped
#    environment:
#      - discovery.type = single-node

  web:
    container_name: elucidate_server
    image: registry.diginfra.net/tt/huc-elucidate-server:1.6.4-SNAPSHOT
    networks:
      - elucidate_network
    env_file:
      - elucidate.env
    depends_on:
      - database
#      - elasticsearch
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - ../../scripts:/scripts
    command: ["/scripts/wait-for-it.sh", "database:5432", "--", "./bin/catalina.sh", "run"]

networks:
  elucidate_network:

volumes:
  database-data:
    driver: local
