/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

val ktor_version = "1.5.0"
val kotlin_serialization = "1.5.0"
val logback_version = "0.20.0"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("http://maven.huygens.knaw.nl/repository")
    }
    mavenCentral()
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

    implementation("io.ktor:ktor-client-cio:$ktor_version")
    implementation("io.ktor:ktor-client-apache:$ktor_version")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.10")
    implementation("com.beust:klaxon:5.0.1")
    implementation("com.github.jsonld-java:jsonld-java:0.13.2")
    implementation("ch.qos.logback:logback-classic:1.3.0-alpha5")
    implementation("com.digirati.elucidate:elucidate-common-lib:1.5.1")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application.
    mainClass.set("huc.di.tt.elucidate.AppKt")
}
