/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package huc.di.tt.elucidate

import com.github.anno4j.Anno4j
import com.github.anno4j.model.Annotation
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun anno4j() {
        val anno4j = Anno4j()

        // Create the base annotation
        val annotation = anno4j.createObject(Annotation::class.java).apply {
            addBodyText("hello world")
            created = "2014-09-28T12:00:00Z"
        }
        println(annotation.resourceAsString)

    }
}
